# Generated by Django 4.0 on 2022-02-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
