# Generated by Django 4.0 on 2022-02-05 12:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0005_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[222, 222], upload_to='product_images/'),
        ),
    ]
