# Generated by Django 4.0 on 2022-02-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0010_productvariant_category_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='esite.productcategory'),
        ),
    ]
