# Generated by Django 4.0 on 2022-02-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0012_alter_productvariant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esite.productcategory'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
