# Generated by Django 4.0 on 2022-02-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0015_remove_product_variant_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esite.productvariant'),
        ),
    ]
